import { MATERIALS } from "./materials.ts";
import type { GuideKind, SimConfig } from "./types.ts";
import { DEFAULT_CONFIG, DEFAULT_GUIDE } from "./types.ts";
import { applyDoseToConfig } from "./euv-dose.ts";

export type RecipePreset = {
  id: string;
  title: string;
  blurb: string;
  cpuUse: string;
  materialId: string;
  config: SimConfig;
};

function baseFromMaterial(materialId: string, nx = 128): SimConfig {
  const m = MATERIALS.find((x) => x.id === materialId) ?? MATERIALS[0];
  const dxNm = (8 * m.L0Nm) / nx;
  return {
    ...DEFAULT_CONFIG,
    nx,
    ny: nx,
    dxNm,
    chiN: m.chiN,
    f: m.f,
    L0Nm: m.L0Nm,
    T: m.TAnnealK,
    guide: { ...DEFAULT_GUIDE },
  };
}

export const PRESETS: RecipePreset[] = [
  {
    id: "line-2x",
    title: "LiNe 2× lamellae",
    blurb: "Sparse chemical stripes at 2 L0. Classic Liu–Nealey density multiplication for line/space.",
    cpuUse: "M1/M0 line/space, dummy fin arrays",
    materialId: "ps-pmma-28",
    config: {
      ...baseFromMaterial("ps-pmma-28"),
      guide: {
        ...DEFAULT_GUIDE,
        kind: "chemo-lamellar",
        LsNm: 56,
        duty: 0.25,
        wetting: 1,
        strength: 1.15,
      },
    },
  },
  {
    id: "line-3x",
    title: "3× pitch multiplication",
    blurb: "Guide period 3 L0, duty ~1/6. Tighter commensurability, more defect-prone.",
    cpuUse: "Tighter metal pitch without denser EUV guides",
    materialId: "ps-pmma-28",
    config: {
      ...baseFromMaterial("ps-pmma-28"),
      guide: {
        ...DEFAULT_GUIDE,
        kind: "chemo-lamellar",
        LsNm: 84,
        duty: 0.17,
        wetting: 1,
        strength: 1.35,
      },
    },
  },
  {
    id: "highchi-metal",
    title: "High-χ 11 nm metal",
    blurb: "Si-containing BCP, L0 = 11 nm, 2× chemo. Proxy for angstrom-era M0.",
    cpuUse: "Sub-10 nm half-pitch interconnect",
    materialId: "si-bcp",
    config: {
      ...baseFromMaterial("si-bcp"),
      chiN: 52,
      guide: {
        ...DEFAULT_GUIDE,
        kind: "chemo-lamellar",
        LsNm: 22,
        duty: 0.25,
        wetting: -1,
        strength: 1.4,
      },
    },
  },
  {
    id: "via-hex",
    title: "Via / contact hex",
    blurb: "Graphoepitaxy wells on a hexagonal lattice. Cylindrical PMMA cores.",
    cpuUse: "Contact-hole shrink, via multiplication",
    materialId: "ps-pmma-cyl",
    config: {
      ...baseFromMaterial("ps-pmma-cyl"),
      guide: {
        ...DEFAULT_GUIDE,
        kind: "contact-holes",
        LsNm: 32,
        duty: 0.4,
        wetting: 1,
        strength: 1.6,
        holeNm: 18,
        wallNm: 7,
      },
    },
  },
  {
    id: "grapho-fins",
    title: "Grapho fin trenches",
    blurb: "Topographic confinement. Walls pin wetting; trench width must be n L0.",
    cpuUse: "Fin-like lines, cut-mask complement",
    materialId: "ps-p2vp",
    config: {
      ...baseFromMaterial("ps-p2vp"),
      guide: {
        ...DEFAULT_GUIDE,
        kind: "grapho-trench",
        LsNm: 48,
        duty: 0.72,
        wetting: 1,
        strength: 1.8,
        wallNm: 6,
      },
    },
  },
  {
    id: "untemplated",
    title: "Untemplated quench",
    blurb: "No guide. Fingerprint lamellae / hex — measures L0, LER of the free film.",
    cpuUse: "Material qualification, SAXS analogue",
    materialId: "ps-pmma-28",
    config: {
      ...baseFromMaterial("ps-pmma-28"),
      noise: 0.03,
      guide: { ...DEFAULT_GUIDE, kind: "none", strength: 0, LsNm: 56 },
    },
  },
  {
    id: "euv-rectify",
    title: "EUV + DSA rectification",
    blurb: "Stochastic EUV guides at 30 mJ/cm² healed by PS-b-PMMA. IMEC/Intel 28 nm full-pitch: DSA cuts LWR and dose.",
    cpuUse: "EUV metal rectification, dose down",
    materialId: "ps-pmma-28",
    config: {
      ...baseFromMaterial("ps-pmma-28"),
      T: 583,
      ...applyDoseToConfig(30, 28),
      tFilmOverL0: 1.5,
      guide: {
        ...DEFAULT_GUIDE,
        kind: "chemo-lamellar",
        LsNm: 28,
        cdNm: 14,
        duty: 0.5,
        wetting: 1,
        strength: 1.05,
      },
    },
  },
  {
    id: "euv-24-1to1",
    title: "24 nm 1:1, no CD trim",
    blurb: "Janes & Innocent-Dolor, SPIE 2026. High-χ 12 nm BCP on 24 nm EUV 1:1. Surface etch without CD trim, LWR/defect data at High-NA-relevant pitch.",
    cpuUse: "CAR extension, High-NA complement",
    materialId: "hchi-12",
    config: {
      ...baseFromMaterial("hchi-12"),
      T: 493,
      T2: 443,
      tSwitch: 7,
      ...applyDoseToConfig(22, 24),
      tFilmOverL0: 1.6,
      guide: {
        ...DEFAULT_GUIDE,
        kind: "chemo-lamellar",
        LsNm: 24,
        cdNm: 12,
        duty: 0.5,
        wetting: 1,
        strength: 1.1,
      },
    },
  },
  {
    id: "imec-p24",
    title: "imec P24 L/S after etch",
    blurb: "SPIE 2026. DSA rectification of pitch-24 nm CAR. After-etch uLWR/uLER target 0.88 / 1.32 nm into TiN, 0.33-NA spec.",
    cpuUse: "Metal L/S CAR extension, after-etch LER",
    materialId: "hchi-12",
    config: {
      ...baseFromMaterial("hchi-12"),
      T: 503,
      T2: 453,
      tSwitch: 6,
      ...applyDoseToConfig(24, 24),
      tFilmOverL0: 1.7,
      deltaGamma: 0.15,
      guide: {
        ...DEFAULT_GUIDE,
        kind: "chemo-lamellar",
        LsNm: 24,
        cdNm: 12,
        duty: 0.5,
        wetting: 1,
        strength: 1.18,
      },
    },
  },
  {
    id: "hex-contact-lcdu",
    title: "Hex contact LCDU",
    blurb: "Do et al. SPIE 2025. High-χ DSA on low-dose EUV hex contacts. Film thickness + anneal + hybrid develop: −62.5% LCDU, −22.8% PPE.",
    cpuUse: "Via/contact stochastics, LCDU/PPE",
    materialId: "ps-pdms",
    config: {
      ...baseFromMaterial("ps-pdms"),
      T: 463,
      tFilmOverL0: 2.4,
      ...applyDoseToConfig(18, 32),
      guide: {
        ...DEFAULT_GUIDE,
        kind: "contact-holes",
        LsNm: 32,
        holeNm: 16,
        wallNm: 6,
        duty: 0.45,
        wetting: 1,
        strength: 1.7,
      },
    },
  },
  {
    id: "via-pair",
    title: "VIA peanut pair",
    blurb: "Zhou et al. arXiv:2510.02715. Two-hole grapho template from superimposed Gaussians (τ, pair). Inverse-co-optimize blend + τ so both cores sit without a redundant domain.",
    cpuUse: "Dual VIA / contact pair, inverse design",
    materialId: "ps-pmma-cyl",
    config: {
      ...baseFromMaterial("ps-pmma-cyl"),
      T: 523,
      blendFrac: 0.22,
      blendPath: "quench",
      tFilmOverL0: 1.8,
      guide: {
        ...DEFAULT_GUIDE,
        kind: "via-pair",
        LsNm: 48,
        holeNm: 14,
        pairNm: 22,
        tau: 0.35,
        wallNm: 6,
        wetting: 1,
        strength: 1.55,
      },
    },
  },
  {
    id: "p4cls-7x",
    title: "P4ClS 7× 7.5 nm",
    blurb: "ACS Appl. Nano Mater. 2025. P4ClS-b-PMA, L0 = 14.1 nm, matched γ, 7× chemo on 193i guides. Feature ~7.5 nm without a topcoat.",
    cpuUse: "Sub-10 nm HP on 193i, 7× multiplication",
    materialId: "p4cls-pma",
    config: {
      ...baseFromMaterial("p4cls-pma"),
      T: 488,
      tFilmOverL0: 1.6,
      guide: {
        ...DEFAULT_GUIDE,
        kind: "chemo-lamellar",
        LsNm: 98.7,
        cdNm: 10,
        duty: 10 / 98.7,
        wetting: 1,
        strength: 1.35,
      },
    },
  },
  {
    id: "maekawa-3x",
    title: "Maekawa 3× sub-10 nm",
    blurb: "PS-b-PGFM, Ls = 3 L0, guide CD in the 0.57–1.0 L0 island. 300 mm, no topcoat, dislocation-free target.",
    cpuUse: "Sub-10 nm HP lines on 300 mm",
    materialId: "ps-pgfm",
    config: {
      ...baseFromMaterial("ps-pgfm"),
      chiN: 32,
      T: 523,
      tFilmOverL0: 1.8,
      guide: {
        ...DEFAULT_GUIDE,
        kind: "chemo-lamellar",
        LsNm: 49.8,
        cdNm: 12,
        duty: 12 / 49.8,
        wetting: 1,
        strength: 1.25,
      },
    },
  },
  {
    id: "highna-24",
    title: "High-NA 24 nm pitch",
    blurb: "A-b-(B-r-C) L0 = 8 nm, 3× chemo. IMEC High-NA DSA goal: pitch below 24 nm.",
    cpuUse: "High-NA EUV complement, CFET metal",
    materialId: "abc-euv",
    config: {
      ...baseFromMaterial("abc-euv"),
      ...applyDoseToConfig(25, 24),
      tFilmOverL0: 2,
      T: 453,
      guide: {
        ...DEFAULT_GUIDE,
        kind: "chemo-lamellar",
        LsNm: 24,
        cdNm: 6,
        duty: 0.25,
        wetting: 1,
        strength: 1.3,
      },
    },
  },
  {
    id: "kinetic-trap",
    title: "High-χ kinetic trap",
    blurb: "Si-BCP at 430 K. Strong segregation, slow chain motion — dislocations freeze. Raise T or microwave to heal.",
    cpuUse: "Anneal-protocol design for high-χ",
    materialId: "si-bcp",
    config: {
      ...baseFromMaterial("si-bcp"),
      T: 430,
      microwave: 1,
      tFilmOverL0: 3.4,
      guide: {
        ...DEFAULT_GUIDE,
        kind: "chemo-lamellar",
        LsNm: 22,
        cdNm: 7,
        duty: 0.32,
        wetting: -1,
        strength: 1.5,
      },
    },
  },
  {
    id: "microwave-4x",
    title: "Microwave 4× PS-PMMA",
    blurb: "Dipolar PMMA heating. 60 s class kinetics, 4-fold density multiplication (Appl. Surf. Sci. 2026).",
    cpuUse: "Fast thermal budget, 4× lines",
    materialId: "ps-pmma-28",
    config: {
      ...baseFromMaterial("ps-pmma-28"),
      microwave: 4.5,
      T: 523,
      tFilmOverL0: 1.2,
      guide: {
        ...DEFAULT_GUIDE,
        kind: "chemo-lamellar",
        LsNm: 112,
        cdNm: 14,
        duty: 0.125,
        wetting: 1,
        strength: 1.4,
      },
    },
  },
  {
    id: "missing-line",
    title: "Missing-stripe repair",
    blurb: "ACS 2026 SEPA. One chemo stripe deleted. Layer-by-layer field decay tests whether the free surface heals the period or traps a dislocation.",
    cpuUse: "Template-defect screening, SEPA",
    materialId: "ps-pmma-28",
    config: {
      ...baseFromMaterial("ps-pmma-28"),
      T: 583,
      tFilmOverL0: 2.2,
      templateDefect: "missing-stripe",
      guide: {
        ...DEFAULT_GUIDE,
        kind: "chemo-lamellar",
        LsNm: 56,
        cdNm: 14,
        duty: 0.25,
        wetting: 1,
        strength: 1.2,
      },
    },
  },
  {
    id: "stitch-seam",
    title: "High-NA stitch seam",
    blurb: "Phase jump at mid-FOV — the overlay cost of 0.55 NA field stitching (Intel/ASML 2026, ~30% throughput hit). DSA may lock a dislocation wall on the seam.",
    cpuUse: "High-NA stitch / large-mask overlay",
    materialId: "hchi-12",
    config: {
      ...baseFromMaterial("hchi-12"),
      T: 493,
      tFilmOverL0: 1.8,
      templateDefect: "stitch",
      ...applyDoseToConfig(24, 24),
      guide: {
        ...DEFAULT_GUIDE,
        kind: "chemo-lamellar",
        LsNm: 24,
        cdNm: 12,
        duty: 0.5,
        overlayNm: 3.5,
        wetting: 1,
        strength: 1.15,
      },
    },
  },
];

export const GUIDE_LABELS: Record<GuideKind, string> = {
  "chemo-lamellar": "Chemoepitaxy stripes",
  "grapho-trench": "Graphoepitaxy trenches",
  "contact-holes": "Contact-hole wells",
  "via-pair": "VIA peanut pair",
  "fin-array": "Fin array + cut",
  none: "Untemplated",
};
