export type DsaWin = {
  id: string;
  recipeId: string;
  title: string;
  year: string;
  source: string;
  bcp: string;
  flow: string;
  l0Nm: number;
  lsNm: number;
  nx: string;
  cdL0: string;
  result: string;
  layer: string;
};

/** Combinations with a published successful wafer / SEM result. Not screening guesses. */
export const DSA_WINS: DsaWin[] = [
  {
    id: "p24",
    recipeId: "imec-p24",
    title: "P24 L/S after-etch rectification",
    year: "2026",
    source: "Vallat, SPIE 13982-23 (imec)",
    bcp: "PS-b-PMMA and high-χ",
    flow: "Chemo 1:1 on EUV CAR, transfer into TiN",
    l0Nm: 24,
    lsNm: 24,
    nx: "1×",
    cdL0: "0.50",
    result: "After-etch uLWR / uLER 0.88 / 1.32 nm. Meets 0.33-NA spec.",
    layer: "Metal L/S",
  },
  {
    id: "euv28",
    recipeId: "euv-rectify",
    title: "EUV + DSA at 28 nm full pitch",
    year: "2025",
    source: "Verstraete / imec, MRS Commun. 15 1269",
    bcp: "PS-b-PMMA",
    flow: "LiNe-class chemo on EUV prepatterns (three CAR resists)",
    l0Nm: 28,
    lsNm: 28,
    nx: "1×",
    cdL0: "0.50",
    result: "SiN hard mask: no defects vs resist, LWR down vs EUV, resist-agnostic.",
    layer: "Metal rectification",
  },
  {
    id: "p24-1to1",
    recipeId: "euv-24-1to1",
    title: "24 nm 1:1, no CD trim",
    year: "2026",
    source: "Janes & Innocent-Dolor, SPIE 2026",
    bcp: "High-χ, L0 ≈ 12 nm",
    flow: "EUV 1:1 chemo, surface etch without trim",
    l0Nm: 12,
    lsNm: 24,
    nx: "2×",
    cdL0: "1.00",
    result: "LWR / defect data at High-NA-relevant pitch without a CD-trim loop.",
    layer: "CAR extension",
  },
  {
    id: "pgfm",
    recipeId: "maekawa-3x",
    title: "PS-b-PGFM dislocation-free 18 nm lines",
    year: "2025",
    source: "Maekawa et al., Adv. Funct. Mater. 35 2421066",
    bcp: "PS-b-PGFM (higher-χ PMMA)",
    flow: "300 mm chemo, 5 min thermal, no topcoat, Ls = 90 nm",
    l0Nm: 18,
    lsNm: 90,
    nx: "5×",
    cdL0: "0.57–1.0",
    result: "Defect-free 1000 µm². PGFM26-7 CD 0.82–1.0 L0; PGFM25-11 CD 0.57–0.87 L0. HP 8.3 nm.",
    layer: "Sub-10 nm HP lines",
  },
  {
    id: "line2x",
    recipeId: "line-2x",
    title: "LiNe 2× PS-b-PMMA",
    year: "2010–26",
    source: "Liu–Nealey flow; 300 mm imec / IBM / TEL",
    bcp: "PS-b-PMMA, L0 ≈ 28 nm",
    flow: "X-PS stripe + O₂ trim + backfill mat, 2× density multiplication",
    l0Nm: 28,
    lsNm: 56,
    nx: "2×",
    cdL0: "~0.5",
    result: "Industrial chemo baseline. Still the flow P24 and PGFM sit on.",
    layer: "M1 / dummy fin L/S",
  },
  {
    id: "line3x",
    recipeId: "line-3x",
    title: "PS-b-PMMA 3× on Ls = 84 nm",
    year: "2025",
    source: "Cited process window in Maekawa AFM 2025",
    bcp: "PS-b-PMMA, L0 = 28 nm",
    flow: "Chemo 3×, PS guides Ls = 84 nm",
    l0Nm: 28,
    lsNm: 84,
    nx: "3×",
    cdL0: "Maekawa island",
    result: "Established 3× window used as the reference for PGFM 5×.",
    layer: "Tighter metal without denser EUV",
  },
  {
    id: "mw4x",
    recipeId: "microwave-4x",
    title: "Microwave 4× PS-b-PMMA",
    year: "2026",
    source: "Appl. Surf. Sci. 745 167508",
    bcp: "PS-b-PMMA lamellae",
    flow: "Chemoepitaxy, 60 s microwave (PMMA dipolar heating)",
    l0Nm: 28,
    lsNm: 112,
    nx: "4×",
    cdL0: "~0.5",
    result: "Fingerprint ξ = 141.5 nm in 60 s; defect-free 4× L/S after transfer.",
    layer: "Fast thermal budget L/S",
  },
  {
    id: "phfma",
    recipeId: "highna-24",
    title: "A-b-(B-r-C) / PHFMA 5×, no topcoat",
    year: "2025",
    source: "MRS Commun. 15 1269 (EUV + DSA prospective)",
    bcp: "PS-b-P(MMA-r-HFMA), χ ≈ 0.14, L0 = 12.4 nm",
    flow: "Chemo on P(S-r-MMA) mat, Ls = 82 nm, 5×, no topcoat",
    l0Nm: 12.4,
    lsNm: 82,
    nx: "5×",
    cdL0: "neutral mat",
    result: "Perpendicular lamellae, excellent DSA on 5× guides without a topcoat.",
    layer: "High-NA complement",
  },
  {
    id: "p4cls",
    recipeId: "p4cls-7x",
    title: "P4ClS-b-PMA 7× at 7.5 nm",
    year: "2025",
    source: "ACS Appl. Nano Mater. 2025",
    bcp: "P4ClS-b-PMA, L0 = 14.1 nm, matched γ",
    flow: "Chemo 7× on 193i, no topcoat",
    l0Nm: 14.1,
    lsNm: 98.7,
    nx: "7×",
    cdL0: "~0.7",
    result: "~7.5 nm features from 193i guides. Matched surface energy, no topcoat.",
    layer: "Sub-10 nm HP on DUV",
  },
  {
    id: "hex-lcdu",
    recipeId: "hex-contact-lcdu",
    title: "High-χ hex contact rectification",
    year: "2025",
    source: "Do et al., SPIE 13686 (EUV 2025)",
    bcp: "New high-χ BCP",
    flow: "Low-dose EUV hex → chemo, thicker film + hybrid develop",
    l0Nm: 32,
    lsNm: 32,
    nx: "1×",
    cdL0: "hole",
    result: "LCDU −62.5%, PPE −22.8% vs the EUV guide.",
    layer: "Via / contact",
  },
  {
    id: "tel-hex",
    recipeId: "via-hex",
    title: "TEL chemo hex holes, 3× shrink",
    year: "2025",
    source: "TEL; Micromachines 16 667 review",
    bcp: "Cylinder-forming BCP",
    flow: "Chemoepitaxy, template 150 nm → DSA 50 nm hex",
    l0Nm: 50,
    lsNm: 150,
    nx: "3×",
    cdL0: "hole",
    result: "LCDU 1.7 nm, placement 3.2 nm (3σ). Earlier TEL 9× to 30 nm pitch also held.",
    layer: "Contact hex array",
  },
  {
    id: "hole-shrink",
    recipeId: "via-hex",
    title: "Acid-cleavable hole shrink",
    year: "2025",
    source: "Zhan et al., Oct 2025",
    bcp: "PS-b-PMMA-CHO (Schiff-base)",
    flow: "Grapho 193i + acetic acid wet strip, TEOS transfer",
    l0Nm: 28,
    lsNm: 32,
    nx: "grapho",
    cdL0: "tunable Mn",
    result: "CD shrink + LCDU up vs template. No UV scission. Minimal CD loss into TEOS.",
    layer: "Contact-hole shrink",
  },
  {
    id: "via-pair",
    recipeId: "via-pair",
    title: "VIA peanut pair (τ ≳ 0.35)",
    year: "2025",
    source: "Zhou et al., arXiv:2510.02715",
    bcp: "Cylinder BCP + short-chain blend",
    flow: "Grapho two-hole Gaussian peanut, quench blend",
    l0Nm: 28,
    lsNm: 48,
    nx: "pair",
    cdL0: "τ ≳ 0.35",
    result: "Both cores sit without a redundant domain when τ is manufacturable.",
    layer: "Dual VIA",
  },
];
